apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: sql-wp-sa-wi-policy
  annotations:
    cnrm.cloud.google.com/project-id: takeoff-tgtest-d837
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: sql-proxy-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:takeoff-tgtest-d837.svc.id.goog[osdk-test/sql-proxy-ksa-wi]
