apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: postgresadmin
  annotations:
    cnrm.cloud.google.com/project-id: takeoff-tgtest-d837
spec:
  instanceRef:
    name: molecule-pgsql
  password:
    value: donotuseme1234