# permissions for end users to edit readonlydbusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonlydbuser-editor-role
rules:
- apiGroups:
  - pgsql.takeoff.io
  resources:
  - readonlydbusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgsql.takeoff.io
  resources:
  - readonlydbusers/status
  verbs:
  - get
