---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create test kind cluster
      command: kind create cluster --name osdk-test --kubeconfig {{ kubeconfig }}
    
    - name: show kubeconfig location
      debug:
        var: kubeconfig
